### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by FractalMind** [dmstr/docker-yii2-app#6]
I'm stock here for 2 days now
I keep getting this error, I don't understand why! In other posts they say to not use localhost cuz it uses mysql.sock... but I dont! **When I get into mycontainer I CAN ping and login into the mysql server** using

mysql -h mariadb -u root -p
OR
mysql -h 172.18.0.4 -u root -p

but with Yii it doesn't work!
## Any idea?
```

 "name": "Exception",
        "message": "SQLSTATE[HY000] [2002] No such file or directory",
        "code": 2002,
        "type": "PDOException",
        "file": "/var/www/html/vendor/yiisoft/yii2/db/Connection.php",
        "line": 660,
        "stack-trace": [
            "#0 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(660): PDO->__construct('mysql:dbname=gt...', 'saas', '######', NULL)",
            "#1 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(586): yii\\db\\Connection->createPdoInstance()",
            "#2 /var/www/html/common/gtb/db/TenantPdo.php(27): yii\\db\\Connection->open()",
            "#3 [internal function]: gtb\\db\\TenantPdo->__construct(Object(yii\\db\\Connection), Array)",
            "#4 /var/www/html/vendor/yiisoft/yii2/di/Container.php(375): ReflectionClass->newInstanceArgs(Array)",
            "#5 /var/www/html/vendor/yiisoft/yii2/di/Container.php(156): yii\\di\\Container->build('gtb\\\\db\\\\TenantPd...', Array, Array)",
            "#6 /var/www/html/vendor/yiisoft/yii2/di/Container.php(174): yii\\di\\Container->get('gtb\\\\db\\\\TenantPd...', Array, Array)",
            "#7 /var/www/html/vendor/filsh/yii2-oauth2-server/Module.php(80): yii\\di\\Container->get('access_token')",
            "#8 /var/www/html/vendor/filsh/yii2-oauth2-server/controllers/RestController.php(25): filsh\\yii2\\oauth2server\\Module->getServer()",
            "#9 [internal function]: filsh\\yii2\\oauth2server\\controllers\\RestController->actionToken()",
            "#10 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)",
            "#11 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction->runWithParams(Array)",
            "#12 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller->runAction('token', Array)",
            "#13 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module->runAction('api2/oauth/toke...', Array)",
            "#14 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))",
            "#15 /var/www/html/backend/web/index.php(17): yii\\base\\Application->run()",
            "#16 {main}"

```
```
'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=172.18.0.4;dbname=db',
            'username' => 'root',
            'password' => '########',
            'charset' => 'utf8',
        ],
```

Host: Ubuntu
_docker-compose.yml_
```
version: '3'
services:
  mycontainer:
    image: nimmis/apache-php7
    ports:
      - "52022:22"
      - "3306:3306"
    container_name: mycontainer
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data}/gtb:/app/gtb:rw
      - ${WEB_ROOT}:/var/www/html:rw
      - ${NGINX_FILES_PATH:-./data}/mycontainer.conf.d:/etc/apache2/conf-enabled:rw
      - ${NGINX_FILES_PATH:-./data}/mycontainer.sites-enabled:/etc/apache2/sites-enabled:rw
  
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ${MARIADB_PATH}:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PWD}

networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
```
